Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.box_version = "20260108.1.1"
  
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096" # 4GB for the VM
    vb.cpus = 2
    vb.name = "DO2-M1"
  end
end