networks:
  gitea:
    external: true

volumes:
  gitea-runner-1:
    driver: local

services:
  runner:
    image: custom-gitea-runner:latest
    container_name: gitea-runner-1
    environment:
      - GITEA_INSTANCE_URL=http://192.168.56.12:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=<GITEA-TOKEN>
      - GITEA_RUNNER_NAME=lab-runner
      - KUBECONFIG=/opt/k3s.yaml
      - GITEA_RUNNER_LABELS=ubuntu-latest:host,self-hosted:host

    networks:
      - gitea
    volumes:
      - gitea-runner-1:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/rancher/k3s/k3s.yaml:/opt/k3s.yaml:ro
    restart: always
