#ENC[AES256_GCM,data:gZx+xRorRIQeTiA5aw==,iv:ye8wRrnVaW0wZjQ7by2znkkIM8pgENftlBlXGNPnHpg=,tag:mFBHEPlChG2HZjFrmC9NaA==,type:comment]
cli_password: ENC[AES256_GCM,data:/FPstoiXrA50dMGiLQ==,iv:giKghMMUR4kb2yPOxRUiZ8IMoQ4KbINhI3wPoSMOIv0=,tag:56TFpSSAcBYIXC49V7Vf2A==,type:str]
srv_password: ENC[AES256_GCM,data:wQiq02nzMgP6hmt4p6hukfvEZgs2rRlOJg==,iv:zfl7o2J1WyOrWQEw3w4EOpib2rTa7FkTVCgR4yKJvG4=,tag:sYdT6sEzCMn9Wmt8bi4qwA==,type:str]
sops:
    age:
        - recipient: age19eej52hl2sgv4v0sgfz45q4zgltrra99km5e4mwf5tg06y5kvqjsgmllu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y0tNUnJYbmxoKytIYWdZ
            VW11TFA4d0YxM2tYRUJUT3BvTk16ZlduTWxrClJvV0VPbENVOWZ3NWhkOTU1ZWF0
            WWdmZk40VTdzQ1ZEL0EvODN6NURoWlUKLS0tIGJ2ZFpBbXEvNWRmRjVwTFBPQnlu
            RTkxY0Z0MHJFWmpaWUJlRE5XMmNhWWcKDqVizdAFYA8Xd3ICqtnmMgwrs6IyXoFf
            fUflifcorMa4Wi6ZX2AFdcOKI8z1OgLBlsiyoFBrdUoHt7RQUty/wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T12:56:12Z"
    mac: ENC[AES256_GCM,data:G291PRy+8dv9zeipeCLoMHO+saDJ8CmejbwG0rY79FZkTbCLhL2nIWRom8b62OHtjmb7VtdB53g8BPpPgvPNB/3NMUlGQ9UUe+t7zfDtRjTdvD5qikzJc3/yRhoAFe7Xt/rEkIAR4O8Gl18gWpBiRkTA7gz7wlkGDGvE+QP0odI=,iv:pQs3gFb/7w2AkutUvPfVpGp/i5Ouf/VceVhNzQguPDM=,tag:DTLMHSz7bL58D/WuhCnnxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
