Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.box_version = "20260108.1.1"
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins.do2.lab"
    jenkins.vm.network "private_network", ip: "192.168.56.11"
    jenkins.vm.synced_folder "vagrant/", "/vagrant"
    jenkins.vm.provider "virtualbox" do |vbox|
      vbox.name = "DO2-M2-1-Jenkins"
      vbox.cpus = 2
      vbox.memory = 4096
    end
  end

  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker.do2.lab"
    docker.vm.network "private_network", ip: "192.168.56.12"
    docker.vm.synced_folder "vagrant/", "/vagrant"
    docker.vm.provider "virtualbox" do |vbox|
      vbox.name = "DO2-M2-2-Docker"
      vbox.cpus = 2
      vbox.memory = 4096
    end
  end
end