#ENC[AES256_GCM,data:HHVyy8ed9KTBFuXy2A==,iv:Oa2n+T6fItaVLFfg/0rBV6n2vbh1rZXemXBtdsX8ZTY=,tag:1lb/uT6MvVzZSdX9UJN5BA==,type:comment]
cli_password: ENC[AES256_GCM,data:0yGqGF7V7LIb92G2Mg==,iv:NVWoRIDQKUAHUR6IFKTNeMhW5mtQEx3qHCqx2NySnjs=,tag:ZoF4SUwc+HMjGzjg0QtLTg==,type:str]
srv_password: ENC[AES256_GCM,data:aExJDqIo0cDae1CUEp6TF76znSygTOG40A==,iv:H9hm6Cs80rvu8rHL/fmZkBfL/Dp2XIcRnToyyeMUq1w=,tag:SpbU/pWznplZd82enSW2kg==,type:str]
sops:
    age:
        - recipient: age1slem7u0vx579uyjved0ns346weefl993n8rzzmuksfqvac8tfvqq9ckazj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NzU3YmZGa1ZBQWZybWZk
            enBDNGJyLzllVEw3V1hkS2lxc3JrV2tZdDAwCjdqYzNCZkh0Y1lXQ0llZUd2TnUv
            VDJNbU1IOTJRdWprbUI1bldxVmRoamcKLS0tIDZuZHpHVmRRbTBiVHJHWlpMYzJk
            UlVyYnpjODhvcVlNMUVxUkxCU01mNGcKcIKCku/J/HpLVRGdKtoy9hlA2+Ppl7M8
            XgkcPlD6ZdB0/XRYp8fJmpWiYRk/t1ERATJ5xWhCEBqbq+GPN6C3JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:15:54Z"
    mac: ENC[AES256_GCM,data:EEYTjlG8hKghUkNSCxVIyYYDaG9uUN4cmxy41tKOqFCgqUiIBgT15tVpCe0FJ+BcuIfdA1g7eOqsZfUKymLBjcRUeQtqaovTeHhtU9PwGF/pdFbBeLGorIfksM0c7kK+z61PvHgTr1lffUhgbU0Vmx3mUi0HDeM5o6RDJrpgQ7U=,iv:/nkRMB/RBSrV0z/MT8s6QqFSi9zg1OMEW3ZQiu+gNvs=,tag:IKNPsSb+m6bsclVx3PzWZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
